git clone https://github.com/kubernetes/website.git ./repos/kubernetes/website
git clone https://github.com/flutter/website.git ./repos/flutter/website
git clone https://github.com/jonbarron/website.git ./repos/jonbarron/website
git clone https://github.com/babel/website.git ./repos/babel/website
git clone https://github.com/emberjs/website.git ./repos/emberjs/website
git clone https://github.com/elementary/website.git ./repos/elementary/website
git clone https://github.com/yarnpkg/website.git ./repos/yarnpkg/website
git clone https://github.com/tachiyomiorg/website.git ./repos/tachiyomiorg/website
git clone https://github.com/letsencrypt/website.git ./repos/letsencrypt/website
git clone https://github.com/mono/website.git ./repos/mono/website
git clone https://github.com/syntaxfm/website.git ./repos/syntaxfm/website
git clone https://github.com/github/personal-website.git ./repos/github/personal-website
git clone https://github.com/hshar/website.git ./repos/hshar/website
git clone https://github.com/CodingTrain/website-archive.git ./repos/CodingTrain/website-archive
git clone https://github.com/OCA/website.git ./repos/OCA/website
git clone https://github.com/hackforla/website.git ./repos/hackforla/website
git clone https://github.com/parcel-bundler/website.git ./repos/parcel-bundler/website
git clone https://github.com/kubeflow/website.git ./repos/kubeflow/website
git clone https://github.com/radix-ui/website.git ./repos/radix-ui/website
git clone https://github.com/thenewboston-blockchain/Website.git ./repos/thenewboston-blockchain/Website
git clone https://github.com/dotnet-foundation/website.git ./repos/dotnet-foundation/website
git clone https://github.com/asyncapi/website.git ./repos/asyncapi/website
git clone https://github.com/learning-zone/website-templates.git ./repos/learning-zone/website-templates
git clone https://github.com/sdmg15/Best-websites-a-programmer-should-visit.git ./repos/sdmg15/Best-websites-a-programmer-should-visit
git clone https://github.com/ethereum/ethereum-org-website.git ./repos/ethereum/ethereum-org-website
git clone https://github.com/agefanscom/website.git ./repos/agefanscom/website
git clone https://github.com/golang/website.git ./repos/golang/website
git clone https://github.com/the-full-stack/website.git ./repos/the-full-stack/website
git clone https://github.com/TheAlgorithms/website.git ./repos/TheAlgorithms/website
git clone https://github.com/tokio-rs/website.git ./repos/tokio-rs/website
git clone https://github.com/COVID19Tracking/website.git ./repos/COVID19Tracking/website
git clone https://github.com/lootproject/website.git ./repos/lootproject/website
git clone https://github.com/facebook/react-native-website.git ./repos/facebook/react-native-website
git clone https://github.com/getredash/website.git ./repos/getredash/website
git clone https://github.com/appveyor/website.git ./repos/appveyor/website
git clone https://github.com/outreachy/website.git ./repos/outreachy/website
git clone https://github.com/BabylonJS/Website.git ./repos/BabylonJS/Website
git clone https://github.com/diem/website.git ./repos/diem/website
git clone https://github.com/Yin-Hongwei/music-website.git ./repos/Yin-Hongwei/music-website
git clone https://github.com/sbt/website.git ./repos/sbt/website
git clone https://github.com/etcd-io/website.git ./repos/etcd-io/website
git clone https://github.com/WebAssembly/website.git ./repos/WebAssembly/website
git clone https://github.com/files-community/Website.git ./repos/files-community/Website
git clone https://github.com/reactjs/react.dev.git ./repos/reactjs/react.dev
git clone https://github.com/cert-manager/website.git ./repos/cert-manager/website
git clone https://github.com/jivoi/awesome-osint.git ./repos/jivoi/awesome-osint
git clone https://github.com/kubesphere/website.git ./repos/kubesphere/website
git clone https://github.com/bloominstituteoftechnology/portfolio-website.git ./repos/bloominstituteoftechnology/portfolio-website
git clone https://github.com/jscraftcamp/website.git ./repos/jscraftcamp/website
git clone https://github.com/flutterchina/website.git ./repos/flutterchina/website
git clone https://github.com/istio/istio.io.git ./repos/istio/istio.io
git clone https://github.com/microsoft/SmartHotel360-Website.git ./repos/microsoft/SmartHotel360-Website
git clone https://github.com/BookStackApp/website.git ./repos/BookStackApp/website
git clone https://github.com/delbaoliveira/website.git ./repos/delbaoliveira/website
git clone https://github.com/869413421/chatgpt-web.git ./repos/869413421/chatgpt-web
git clone https://github.com/fluxcd/website.git ./repos/fluxcd/website
git clone https://github.com/microsoft/TailwindTraders-Website.git ./repos/microsoft/TailwindTraders-Website
git clone https://github.com/gin-gonic/website.git ./repos/gin-gonic/website
git clone https://github.com/twitter/opensource-website.git ./repos/twitter/opensource-website
git clone https://github.com/smaranjitghose/awesome-portfolio-websites.git ./repos/smaranjitghose/awesome-portfolio-websites
git clone https://github.com/openstreetmap/openstreetmap-website.git ./repos/openstreetmap/openstreetmap-website
git clone https://github.com/cake-build/website.git ./repos/cake-build/website
git clone https://github.com/microsoft/TypeScript-Website.git ./repos/microsoft/TypeScript-Website
git clone https://github.com/exercism/website.git ./repos/exercism/website
git clone https://github.com/ipfs-inactive/website.git ./repos/ipfs-inactive/website
git clone https://github.com/destinygg/website.git ./repos/destinygg/website
git clone https://github.com/adrianhajdin/portfolio_website.git ./repos/adrianhajdin/portfolio_website
git clone https://github.com/techqueria/website.git ./repos/techqueria/website
git clone https://github.com/nuxt/website-v2.git ./repos/nuxt/website-v2
git clone https://github.com/ProseMirror/website.git ./repos/ProseMirror/website
git clone https://github.com/fengjinqi/website.git ./repos/fengjinqi/website
git clone https://github.com/discordjs/website.git ./repos/discordjs/website
git clone https://github.com/caddyserver/website.git ./repos/caddyserver/website
git clone https://github.com/holy-unblocker/website-aio.git ./repos/holy-unblocker/website-aio
git clone https://github.com/rampatra/wedding-website.git ./repos/rampatra/wedding-website
git clone https://github.com/flet-dev/website.git ./repos/flet-dev/website
git clone https://github.com/phalcon/website.git ./repos/phalcon/website
git clone https://github.com/bedimcode/responsive-portfolio-website-Alexa.git ./repos/bedimcode/responsive-portfolio-website-Alexa
git clone https://github.com/Ping-Foundation/Yeng-Website.git ./repos/Ping-Foundation/Yeng-Website
git clone https://github.com/linkerd/website.git ./repos/linkerd/website
git clone https://github.com/risk-first/website.git ./repos/risk-first/website
git clone https://github.com/redhat-openstack/website.git ./repos/redhat-openstack/website
git clone https://github.com/okfn/website.git ./repos/okfn/website
git clone https://github.com/certbot/website.git ./repos/certbot/website
git clone https://github.com/facebook/docusaurus.git ./repos/facebook/docusaurus
git clone https://github.com/lutris/website.git ./repos/lutris/website
git clone https://github.com/dharmanshu9930/Website.git ./repos/dharmanshu9930/Website
git clone https://github.com/holy-unblocker/website.git ./repos/holy-unblocker/website
git clone https://github.com/vitessio/website.git ./repos/vitessio/website
git clone https://github.com/pallets/website.git ./repos/pallets/website
git clone https://github.com/nf-core/website.git ./repos/nf-core/website
git clone https://github.com/swcarpentry/website.git ./repos/swcarpentry/website
git clone https://github.com/appwrite/website.git ./repos/appwrite/website
git clone https://github.com/sagemath/website.git ./repos/sagemath/website
git clone https://github.com/pallets/flask-website.git ./repos/pallets/flask-website
git clone https://github.com/jikan-me/website.git ./repos/jikan-me/website
git clone https://github.com/swc-project/website.git ./repos/swc-project/website
git clone https://github.com/datenanfragen/website.git ./repos/datenanfragen/website
git clone https://github.com/tektoncd/website.git ./repos/tektoncd/website
git clone https://github.com/nodejs/nodejs.org.git ./repos/nodejs/nodejs.org
git clone https://github.com/grid-js/website.git ./repos/grid-js/website
git clone https://github.com/mqtt/mqtt.org.git ./repos/mqtt/mqtt.org
git clone https://github.com/designmodo/html-website-templates.git ./repos/designmodo/html-website-templates
git clone https://github.com/developedbyed/glass-website.git ./repos/developedbyed/glass-website
git clone https://github.com/briancodex/react-website-v1.git ./repos/briancodex/react-website-v1
git clone https://github.com/bitcoin-dot-org/Bitcoin.org.git ./repos/bitcoin-dot-org/Bitcoin.org
git clone https://github.com/kubeedge/website.git ./repos/kubeedge/website
git clone https://github.com/apache/dubbo-website.git ./repos/apache/dubbo-website
git clone https://github.com/rabbitmq/rabbitmq-website.git ./repos/rabbitmq/rabbitmq-website
git clone https://github.com/bettercap/website.git ./repos/bettercap/website
git clone https://github.com/newrelic/docs-website.git ./repos/newrelic/docs-website
git clone https://github.com/gohugoio/hugo.git ./repos/gohugoio/hugo
git clone https://github.com/pyslackers/website.git ./repos/pyslackers/website
git clone https://github.com/AhmadIbrahiim/Website-downloader.git ./repos/AhmadIbrahiim/Website-downloader
git clone https://github.com/tuteng/Best-websites-a-programmer-should-visit-zh.git ./repos/tuteng/Best-websites-a-programmer-should-visit-zh
git clone https://github.com/umami-software/website.git ./repos/umami-software/website
git clone https://github.com/sindresorhus/pageres.git ./repos/sindresorhus/pageres
git clone https://github.com/code4sabae/website.git ./repos/code4sabae/website
git clone https://github.com/goharbor/website.git ./repos/goharbor/website
git clone https://github.com/RikkaApps/websites.git ./repos/RikkaApps/websites
git clone https://github.com/exercism/website-copy.git ./repos/exercism/website-copy
git clone https://github.com/kserve/website.git ./repos/kserve/website
git clone https://github.com/bradtraversy/loruki-website.git ./repos/bradtraversy/loruki-website
git clone https://github.com/flathub-infra/website.git ./repos/flathub-infra/website
git clone https://github.com/phpmyadmin/website.git ./repos/phpmyadmin/website
git clone https://github.com/AgileVentures/WebsiteOne.git ./repos/AgileVentures/WebsiteOne
git clone https://github.com/akashyap2013/PortFolio_Website.git ./repos/akashyap2013/PortFolio_Website
git clone https://github.com/electron/website.git ./repos/electron/website
git clone https://github.com/gleam-lang/website.git ./repos/gleam-lang/website
git clone https://github.com/nim-lang/website.git ./repos/nim-lang/website
git clone https://github.com/Paperback-iOS/website.git ./repos/Paperback-iOS/website
git clone https://github.com/wirtzdan/website.git ./repos/wirtzdan/website
git clone https://github.com/bobangajicsm/react-portfolio-website.git ./repos/bobangajicsm/react-portfolio-website
git clone https://github.com/reactiveui/website.git ./repos/reactiveui/website
git clone https://github.com/pmndrs/website.git ./repos/pmndrs/website
git clone https://github.com/vlang/website.git ./repos/vlang/website
git clone https://github.com/payloadcms/website.git ./repos/payloadcms/website
git clone https://github.com/akashyap2013/Blooger_Website.git ./repos/akashyap2013/Blooger_Website
git clone https://github.com/ndapp/WebSite.git ./repos/ndapp/WebSite
git clone https://github.com/scratchapixel/website.git ./repos/scratchapixel/website
git clone https://github.com/carbon-design-system/carbon-website.git ./repos/carbon-design-system/carbon-website
git clone https://github.com/honojs/website.git ./repos/honojs/website
git clone https://github.com/ghtorrent/ghtorrent.org.git ./repos/ghtorrent/ghtorrent.org
git clone https://github.com/bitcoin-core-review-club/website.git ./repos/bitcoin-core-review-club/website
git clone https://github.com/magcius/noclip.website.git ./repos/magcius/noclip.website
git clone https://github.com/haiku/website.git ./repos/haiku/website
git clone https://github.com/electron/electronjs.org-old.git ./repos/electron/electronjs.org-old
git clone https://github.com/FOSDEM/website.git ./repos/FOSDEM/website
git clone https://github.com/kyverno/website.git ./repos/kyverno/website
git clone https://github.com/canonical-web-and-design/tutorials.ubuntu.com.git ./repos/canonical-web-and-design/tutorials.ubuntu.com
git clone https://github.com/Chia-Network/website.git ./repos/Chia-Network/website
git clone https://github.com/uvham521/WebStack-Laravel.git ./repos/uvham521/WebStack-Laravel
git clone https://github.com/fieldtrip/website.git ./repos/fieldtrip/website
git clone https://github.com/boostorg/website.git ./repos/boostorg/website
git clone https://github.com/longhorn/website.git ./repos/longhorn/website
git clone https://github.com/maunium/dontasktoask.com.git ./repos/maunium/dontasktoask.com
git clone https://github.com/neondatabase/website.git ./repos/neondatabase/website
git clone https://github.com/lerna/website.git ./repos/lerna/website
git clone https://github.com/myles/awesome-static-generators.git ./repos/myles/awesome-static-generators
git clone https://github.com/afsy/website.git ./repos/afsy/website
git clone https://github.com/maunium/dontasktoask.com.git ./repos/maunium/dontasktoask.com
git clone https://github.com/neondatabase/website.git ./repos/neondatabase/website
git clone https://github.com/lerna/website.git ./repos/lerna/website
git clone https://github.com/myles/awesome-static-generators.git ./repos/myles/awesome-static-generators
git clone https://github.com/afsy/website.git ./repos/afsy/website
git clone https://github.com/banago/simple-php-website.git ./repos/banago/simple-php-website
git clone https://github.com/contentlayerdev/website.git ./repos/contentlayerdev/website
git clone https://github.com/AssemblyScript/website.git ./repos/AssemblyScript/website
git clone https://github.com/livecoders/website.git ./repos/livecoders/website
git clone https://github.com/the-guild-org/website.git ./repos/the-guild-org/website
git clone https://github.com/OriginCloud/Website.git ./repos/OriginCloud/Website
git clone https://github.com/gdg-x/hoverboard.git ./repos/gdg-x/hoverboard
git clone https://github.com/serverless-components/website.git ./repos/serverless-components/website
git clone https://github.com/kyma-project/website.git ./repos/kyma-project/website
git clone https://github.com/codewithsadee/anon-ecommerce-website.git ./repos/codewithsadee/anon-ecommerce-website
git clone https://github.com/sharecuts/website.git ./repos/sharecuts/website
git clone https://github.com/eggsy/website.git ./repos/eggsy/website
git clone https://github.com/kubesimplify/website.git ./repos/kubesimplify/website
git clone https://github.com/peachananr/onepage-scroll.git ./repos/peachananr/onepage-scroll
git clone https://github.com/socketio/socket.io-website.git ./repos/socketio/socket.io-website
git clone https://github.com/rails/website.git ./repos/rails/website
git clone https://github.com/styled-components/styled-components-website.git ./repos/styled-components/styled-components-website
git clone https://github.com/carlosazaustre/website.git ./repos/carlosazaustre/website
git clone https://github.com/sunnah-com/website.git ./repos/sunnah-com/website
git clone https://github.com/karmada-io/website.git ./repos/karmada-io/website
git clone https://github.com/grammyjs/website.git ./repos/grammyjs/website
git clone https://github.com/servicemesher/website.git ./repos/servicemesher/website
git clone https://github.com/girldevelopit/gdi-website.git ./repos/girldevelopit/gdi-website
git clone https://github.com/softwarecrafters/website.git ./repos/softwarecrafters/website
git clone https://github.com/linuxkerneltravel/website.git ./repos/linuxkerneltravel/website
git clone https://github.com/xroche/httrack.git ./repos/xroche/httrack
git clone https://github.com/0xProject/website.git ./repos/0xProject/website
git clone https://github.com/website-scraper/node-website-scraper.git ./repos/website-scraper/node-website-scraper
git clone https://github.com/chaoss/website.git ./repos/chaoss/website
git clone https://github.com/XMuli/website.git ./repos/XMuli/website
git clone https://github.com/kentcdodds/kentcdodds.com.git ./repos/kentcdodds/kentcdodds.com
git clone https://github.com/expressjs/expressjs.com.git ./repos/expressjs/expressjs.com
git clone https://github.com/tailwindlabs/tailwindcss.com.git ./repos/tailwindlabs/tailwindcss.com
git clone https://github.com/scm-ninja/starter-web.git ./repos/scm-ninja/starter-web
git clone https://github.com/dart-lang/site-www.git ./repos/dart-lang/site-www
git clone https://github.com/usegalaxy-eu/website.git ./repos/usegalaxy-eu/website
git clone https://github.com/bedimcode/responsive-website-restaurant.git ./repos/bedimcode/responsive-website-restaurant
git clone https://github.com/api-platform/website.git ./repos/api-platform/website
git clone https://github.com/BuckyMaler/global.git ./repos/BuckyMaler/global
git clone https://github.com/yenchiah/project-website-template.git ./repos/yenchiah/project-website-template
git clone https://github.com/microsoft/project-html-website.git ./repos/microsoft/project-html-website
git clone https://github.com/OpenClassrooms-Student-Center/GameOn-website-FR.git ./repos/OpenClassrooms-Student-Center/GameOn-website-FR
git clone https://github.com/ubports/docs.ubports.com.git ./repos/ubports/docs.ubports.com
git clone https://github.com/starknet-io/starknet-website.git ./repos/starknet-io/starknet-website
git clone https://github.com/chaos-mesh/website.git ./repos/chaos-mesh/website
git clone https://github.com/verdaccio/website.git ./repos/verdaccio/website
git clone https://github.com/Xuanwo/WebsitesForStudents.git ./repos/Xuanwo/WebsitesForStudents
git clone https://github.com/unstoppabledomains/decentralized-websites.git ./repos/unstoppabledomains/decentralized-websites
git clone https://github.com/buckyroberts/Spider.git ./repos/buckyroberts/Spider
git clone https://github.com/OverTheWireOrg/OverTheWire-website.git ./repos/OverTheWireOrg/OverTheWire-website
git clone https://github.com/laurilehmijoki/s3_website.git ./repos/laurilehmijoki/s3_website
git clone https://github.com/sctoCloud/Website.git ./repos/sctoCloud/Website
git clone https://github.com/divanov11/portfolio-website.git ./repos/divanov11/portfolio-website
git clone https://github.com/academicpages/academicpages.git ./repos/ub.io.git ./repos/academicpages/academicpages.git ./repos/ub.io
git clone https://github.com/corona-warn-app/cwa-website.git ./repos/corona-warn-app/cwa-website
git clone https://github.com/bedimcode/responsive-travel-website.git ./repos/bedimcode/responsive-travel-website
git clone https://github.com/hashicorp/terraform-website.git ./repos/hashicorp/terraform-website
git clone https://github.com/bradtraversy/bootstrap-bootcamp-website.git ./repos/bradtraversy/bootstrap-bootcamp-website
git clone https://github.com/verekia/initializr-website.git ./repos/verekia/initializr-website
git clone https://github.com/kisslinux/website.git ./repos/kisslinux/website
git clone https://github.com/geotribu/website.git ./repos/geotribu/website
git clone https://github.com/TheOdinProject/theodinproject.git ./repos/TheOdinProject/theodinproject
git clone https://github.com/EvilInsultGenerator/website.git ./repos/EvilInsultGenerator/website
git clone https://github.com/hexojs/site.git ./repos/hexojs/site
git clone https://github.com/sindresorhus/capture-website.git ./repos/sindresorhus/capture-website
git clone https://github.com/tianocore/tianocore.git ./repos/ub.io.git ./repos/tianocore/tianocore.git ./repos/ub.io
git clone https://github.com/yeoman/yeoman.io.git ./repos/yeoman/yeoman.io
git clone https://github.com/momentum-mod/website.git ./repos/momentum-mod/website
git clone https://github.com/nolimits4web/swiper-website.git ./repos/nolimits4web/swiper-website
git clone https://github.com/angular-ui/ui-grid.info.git ./repos/angular-ui/ui-grid.info
git clone https://github.com/TeamNewPipe/website.git ./repos/TeamNewPipe/website
git clone https://github.com/Neovenchy/Discord-bot-website-template.git ./repos/Neovenchy/Discord-bot-website-template
git clone https://github.com/luksa/kubia-website-example.git ./repos/luksa/kubia-website-example
git clone https://github.com/erlef/website.git ./repos/erlef/website
git clone https://github.com/cdnjs/new-website.git ./repos/cdnjs/new-website
git clone https://github.com/ShaifArfan/one-page-website-html-css-project.git ./repos/ShaifArfan/one-page-website-html-css-project
git clone https://github.com/hh1977/Website.git ./repos/hh1977/Website
git clone https://github.com/amfoss/website.git ./repos/amfoss/website
git clone https://github.com/GDQuest/website.git ./repos/GDQuest/website
git clone https://github.com/laraveluk/website.git ./repos/laraveluk/website
git clone https://github.com/AnoyiX/anoyi.git ./repos/AnoyiX/anoyi
git clone https://github.com/nko/website.git ./repos/nko/website
git clone https://github.com/pwdhash/website.git ./repos/pwdhash/website
git clone https://github.com/luckyframework/website.git ./repos/luckyframework/website
git clone https://github.com/o-botics/website.git ./repos/o-botics/website
git clone https://github.com/WeblateOrg/website.git ./repos/WeblateOrg/website
git clone https://github.com/hammerjs/hammerjs.git ./repos/ub.io.git ./repos/hammerjs/hammerjs.git ./repos/ub.io
git clone https://github.com/developer-portal/website.git ./repos/developer-portal/website
git clone https://github.com/quarto-dev/quarto-web.git ./repos/quarto-dev/quarto-web
git clone https://github.com/PreMiD/Website.git ./repos/PreMiD/Website
git clone https://github.com/elixir-lang/elixir-lang.git ./repos/ub.com.git ./repos/elixir-lang/elixir-lang.git ./repos/ub.com
git clone https://github.com/hundredrabbits/100r.co.git ./repos/hundredrabbits/100r.co
git clone https://github.com/jacobtomlinson/website.git ./repos/jacobtomlinson/website
git clone https://github.com/marcosrivasr/bootstrap5-website.git ./repos/marcosrivasr/bootstrap5-website
git clone https://github.com/navidrome/website.git ./repos/navidrome/website
git clone https://github.com/GuGeYun/Website.git ./repos/GuGeYun/Website
git clone https://github.com/mpa139/allanlab.git ./repos/mpa139/allanlab
git clone https://github.com/snowex-hackweek/website.git ./repos/snowex-hackweek/website
git clone https://github.com/gotify/website.git ./repos/gotify/website
git clone https://github.com/ChrisTitusTech/website.git ./repos/ChrisTitusTech/website
git clone https://github.com/cloudacademy/static-website-example.git ./repos/cloudacademy/static-website-example
git clone https://github.com/ratatui-org/website.git ./repos/ratatui-org/website
git clone https://github.com/anfederico/flaskex.git ./repos/anfederico/flaskex
git clone https://github.com/Warzone/website.git ./repos/Warzone/website
git clone https://github.com/knative/website.git ./repos/knative/website
git clone https://github.com/tidy-finance/website.git ./repos/tidy-finance/website
git clone https://github.com/ByteGrad/portfolio-website.git ./repos/ByteGrad/portfolio-website
git clone https://github.com/framework7io/framework7-website.git ./repos/framework7io/framework7-website
git clone https://github.com/processing/p5.js-website.git ./repos/processing/p5.js-website
git clone https://github.com/CindyJS/website.git ./repos/CindyJS/website
git clone https://github.com/ImageMagick/Website.git ./repos/ImageMagick/Website
git clone https://github.com/slimphp/Slim-Website.git ./repos/slimphp/Slim-Website
git clone https://github.com/jobguywork/website.git ./repos/jobguywork/website
git clone https://github.com/usds/website.git ./repos/usds/website
git clone https://github.com/DiogoMRSilva/websitesVulnerableToSSTI.git ./repos/DiogoMRSilva/websitesVulnerableToSSTI
git clone https://github.com/ddgksf2013/WebSite.git ./repos/ddgksf2013/WebSite
git clone https://github.com/breatheco-de/exercise-collaborative-html-website.git ./repos/breatheco-de/exercise-collaborative-html-website
git clone https://github.com/gblazex/smoothscroll-for-websites.git ./repos/gblazex/smoothscroll-for-websites
git clone https://github.com/apache/echarts-website.git ./repos/apache/echarts-website
git clone https://github.com/UQComputingSociety/website.git ./repos/UQComputingSociety/website
git clone https://github.com/google/web-starter-kit.git ./repos/google/web-starter-kit
git clone https://github.com/sledilnik/website.git ./repos/sledilnik/website
git clone https://github.com/bedimcode/responsive-halloween-website.git ./repos/bedimcode/responsive-halloween-website
git clone https://github.com/zolplay-cn/website.git ./repos/zolplay-cn/website
git clone https://github.com/w3champions/website.git ./repos/w3champions/website
git clone https://github.com/yeecord/website.git ./repos/yeecord/website
git clone https://github.com/scala/docs.scala-lang.git ./repos/scala/docs.scala-lang
git clone https://github.com/emfcamp/Website.git ./repos/emfcamp/Website
git clone https://github.com/Avdan-OS/Website.git ./repos/Avdan-OS/Website
git clone https://github.com/LukeSmithxyz/based.cooking.git ./repos/LukeSmithxyz/based.cooking
git clone https://github.com/czue/django-wedding-website.git ./repos/czue/django-wedding-website
git clone https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website.git ./repos/QAZIMAAZARSHAD/Movie-Streaming-Website
git clone https://github.com/meteor-vegas/website.git ./repos/meteor-vegas/website
git clone https://github.com/mustache/mustache.git ./repos/ub.com.git ./repos/mustache/mustache.git ./repos/ub.com
git clone https://github.com/PretendoNetwork/website.git ./repos/PretendoNetwork/website
git clone https://github.com/DevOpsBootcamp/website.git ./repos/DevOpsBootcamp/website
git clone https://github.com/crimethinc/website.git ./repos/crimethinc/website
git clone https://github.com/withastro/docs.git ./repos/withastro/docs
git clone https://github.com/bradtraversy/modern_portfolio.git ./repos/bradtraversy/modern_portfolio
git clone https://github.com/kanboard/website.git ./repos/kanboard/website
git clone https://github.com/bevyengine/bevy-website.git ./repos/bevyengine/bevy-website
git clone https://github.com/OsProgramadores/op-website-hugo.git ./repos/OsProgramadores/op-website-hugo
git clone https://github.com/itpp-labs/website-addons.git ./repos/itpp-labs/website-addons
git clone https://github.com/tengbao/vanta.git ./repos/tengbao/vanta
git clone https://github.com/moment/momentjs.com.git ./repos/moment/momentjs.com
git clone https://github.com/flybywiresim/website.git ./repos/flybywiresim/website
git clone https://github.com/YaninaTrekhleb/restaurant-website.git ./repos/YaninaTrekhleb/restaurant-website
git clone https://github.com/givanz/VvvebJs.git ./repos/givanz/VvvebJs
git clone https://github.com/The-WebOps-Club/personal-website-template.git ./repos/The-WebOps-Club/personal-website-template
git clone https://github.com/dpc761218914/company_website.git ./repos/dpc761218914/company_website
git clone https://github.com/actix/actix-website.git ./repos/actix/actix-website
git clone https://github.com/jazzband/website.git ./repos/jazzband/website
git clone https://github.com/HITK-TECH-Community/Community-Website.git ./repos/HITK-TECH-Community/Community-Website
git clone https://github.com/qgis/QGIS-Website.git ./repos/qgis/QGIS-Website
git clone https://github.com/snowdream/awesome-android.git ./repos/snowdream/awesome-android
git clone https://github.com/lassiecoder/E-CommerceWebsite.git ./repos/lassiecoder/E-CommerceWebsite
git clone https://github.com/pclubuiet/website.git ./repos/pclubuiet/website
git clone https://github.com/taikoxyz/website.git ./repos/taikoxyz/website
git clone https://github.com/opensearch-project/project-website.git ./repos/opensearch-project/project-website
git clone https://github.com/denoland/dotland.git ./repos/denoland/dotland
git clone https://github.com/WeAllCode/website.git ./repos/WeAllCode/website
git clone https://github.com/96boards/website.git ./repos/96boards/website
git clone https://github.com/tikv/website.git ./repos/tikv/website
git clone https://github.com/novuhq/hacksquad-website.git ./repos/novuhq/hacksquad-website
git clone https://github.com/apache/netbeans-website.git ./repos/apache/netbeans-website
git clone https://github.com/HelloZeroNet/ZeroNet.git ./repos/HelloZeroNet/ZeroNet
git clone https://github.com/wangdoc/website.git ./repos/wangdoc/website
git clone https://github.com/thedaviddias/Front-End-Checklist.git ./repos/thedaviddias/Front-End-Checklist
git clone https://github.com/SeleniumHQ/seleniumhq.git ./repos/ub.io.git ./repos/SeleniumHQ/seleniumhq.git ./repos/ub.io
git clone https://github.com/agarrharr/awesome-static-website-services.git ./repos/agarrharr/awesome-static-website-services
git clone https://github.com/akashyap2013/Mobile_Shopee-E-Commerce-Website.git ./repos/akashyap2013/Mobile_Shopee-E-Commerce-Website
git clone https://github.com/React-Robins/website.git ./repos/React-Robins/website
git clone https://github.com/SauravMukherjee44/CodeIN-Community-Website.git ./repos/SauravMukherjee44/CodeIN-Community-Website
git clone https://github.com/danielkhan/building-website-nodejs-express.git ./repos/danielkhan/building-website-nodejs-express
git clone https://github.com/browserify/browserify-website.git ./repos/browserify/browserify-website
git clone https://github.com/NageshMandal/Engineering-Notes-Website.git ./repos/NageshMandal/Engineering-Notes-Website
git clone https://github.com/sigsep/website.git ./repos/sigsep/website
git clone https://github.com/Linaro/website.git ./repos/Linaro/website
git clone https://github.com/bchiang7/v4.git ./repos/bchiang7/v4
git clone https://github.com/ampproject/amp.dev.git ./repos/ampproject/amp.dev
git clone https://github.com/michael/editable-website.git ./repos/michael/editable-website
git clone https://github.com/lirantal/is-website-vulnerable.git ./repos/lirantal/is-website-vulnerable
git clone https://github.com/eslint/archive-website.git ./repos/eslint/archive-website
git clone https://github.com/opensearch-project/documentation-website.git ./repos/opensearch-project/documentation-website
git clone https://github.com/Bhaney44/ChoiceCoin.git ./repos/ub.io.git ./repos/Bhaney44/ChoiceCoin.git ./repos/ub.io
git clone https://github.com/the-benchmarker/website.git ./repos/the-benchmarker/website
git clone https://github.com/pibook/site.git ./repos/pibook/site
git clone https://github.com/Effect-TS/website.git ./repos/Effect-TS/website
git clone https://github.com/FreeRDP/freerdp.git ./repos/ub.io.git ./repos/FreeRDP/freerdp.git ./repos/ub.io
git clone https://github.com/msgpack/website.git ./repos/msgpack/website
git clone https://github.com/alii/website.git ./repos/alii/website
git clone https://github.com/liyunkun11/official-website.git ./repos/liyunkun11/official-website
git clone https://github.com/keep-network/website.git ./repos/keep-network/website
git clone https://github.com/datacommonsorg/website.git ./repos/datacommonsorg/website
git clone https://github.com/GoogleChrome/related-website-sets.git ./repos/GoogleChrome/related-website-sets
git clone https://github.com/pidcodes/pidcodes.git ./repos/ub.com.git ./repos/pidcodes/pidcodes.git ./repos/ub.com
git clone https://github.com/greenelab/lab-website-template.git ./repos/greenelab/lab-website-template
git clone https://github.com/mitre-attack/attack-website.git ./repos/mitre-attack/attack-website
git clone https://github.com/jigar-sable/Portfolio-Website.git ./repos/jigar-sable/Portfolio-Website
git clone https://github.com/fossasia/fossasia.org.git ./repos/fossasia/fossasia.org
git clone https://github.com/Sta199-S18/website.git ./repos/Sta199-S18/website
git clone https://github.com/safak/movie-website.git ./repos/safak/movie-website
git clone https://github.com/tilburgsciencehub/website.git ./repos/tilburgsciencehub/website
git clone https://github.com/wpcodevo/phone_website.git ./repos/wpcodevo/phone_website
git clone https://github.com/melanierichards/just-build-websites.git ./repos/melanierichards/just-build-websites
git clone https://github.com/Milkdown/website.git ./repos/Milkdown/website
git clone https://github.com/apache/dolphinscheduler-website.git ./repos/apache/dolphinscheduler-website
git clone https://github.com/neon-bindings/website.git ./repos/neon-bindings/website
git clone https://github.com/openssl/web.git ./repos/openssl/web
git clone https://github.com/edk2-porting/renegade-project.org.git ./repos/edk2-porting/renegade-project.org
git clone https://github.com/tutsplus/build-complete-website-expressjs.git ./repos/tutsplus/build-complete-website-expressjs
git clone https://github.com/Aniuyyds/ChatGPT-website.git ./repos/Aniuyyds/ChatGPT-website
git clone https://github.com/mootools/website.git ./repos/mootools/website
git clone https://github.com/diracdeltas/FastestWebsiteEver.git ./repos/diracdeltas/FastestWebsiteEver
git clone https://github.com/RSS-Bridge/rss-bridge.git ./repos/RSS-Bridge/rss-bridge
git clone https://github.com/fastify/website.git ./repos/fastify/website
git clone https://github.com/brianlovin/briOS.git ./repos/brianlovin/briOS
git clone https://github.com/discordextremelist/website.git ./repos/discordextremelist/website
git clone https://github.com/varadbhogayata/varadbhogayata.git ./repos/ub.io.git ./repos/varadbhogayata/varadbhogayata.git ./repos/ub.io
git clone https://github.com/abuanwar072/Protfolio-Website-Flutter-Web.git ./repos/abuanwar072/Protfolio-Website-Flutter-Web
git clone https://github.com/flexdinesh/dev-landing-page.git ./repos/flexdinesh/dev-landing-page
git clone https://github.com/STAT545-UBC/STAT545-UBC-original-website.git ./repos/STAT545-UBC/STAT545-UBC-original-website
git clone https://github.com/KlasenK/website.git ./repos/KlasenK/website
git clone https://github.com/pattern-lab/website.git ./repos/pattern-lab/website
git clone https://github.com/cdk-dev/website.git ./repos/cdk-dev/website
git clone https://github.com/bedimcode/responsive-watches-website.git ./repos/bedimcode/responsive-watches-website
git clone https://github.com/apache/shenyu-website.git ./repos/apache/shenyu-website
git clone https://github.com/mizhexiaoxiao/WebsiteGuide.git ./repos/mizhexiaoxiao/WebsiteGuide
git clone https://github.com/iron-fish/website.git ./repos/iron-fish/website
git clone https://github.com/Loogeek/douban_Website.git ./repos/Loogeek/douban_Website
git clone https://github.com/JuliaLang/www.julialang.org.git ./repos/JuliaLang/www.julialang.org
git clone https://github.com/codemirror/website.git ./repos/codemirror/website
git clone https://github.com/Codelessly/FlutterMinimalWebsite.git ./repos/Codelessly/FlutterMinimalWebsite
git clone https://github.com/developersIndia/website.git ./repos/developersIndia/website
git clone https://github.com/The-MMORPG-Project/website.git ./repos/The-MMORPG-Project/website
git clone https://github.com/multiformats/website.git ./repos/multiformats/website
git clone https://github.com/taofed/website.git ./repos/taofed/website
git clone https://github.com/TokTok/website.git ./repos/TokTok/website
git clone https://github.com/NYC-Camp/website.git ./repos/NYC-Camp/website
git clone https://github.com/justdjango/django-ecommerce.git ./repos/justdjango/django-ecommerce
git clone https://github.com/SampurnaC/portfolio_website_fcc.git ./repos/SampurnaC/portfolio_website_fcc
git clone https://github.com/blitz-js/blitzjs.com.git ./repos/blitz-js/blitzjs.com
git clone https://github.com/bradtraversy/creative-agency-website.git ./repos/bradtraversy/creative-agency-website
git clone https://github.com/kubesphere-retired/docs.kubesphere.io.git ./repos/kubesphere-retired/docs.kubesphere.io
git clone https://github.com/mayooear/langchain-supabase-website-chatbot.git ./repos/mayooear/langchain-supabase-website-chatbot
git clone https://github.com/tdwg/website.git ./repos/tdwg/website
git clone https://github.com/foss-events/website.git ./repos/foss-events/website
git clone https://github.com/grails-samples/grails-website.git ./repos/grails-samples/grails-website
git clone https://github.com/MetaMask/website.git ./repos/MetaMask/website
git clone https://github.com/ooni/ooni.org.git ./repos/ooni/ooni.org
git clone https://github.com/v2fly/v2fly-github-io.git ./repos/v2fly/v2fly-github-io
git clone https://github.com/horchatajs/website.git ./repos/horchatajs/website
git clone https://github.com/novuhq/website.git ./repos/novuhq/website
git clone https://github.com/henryjeff/portfolio-website.git ./repos/henryjeff/portfolio-website
git clone https://github.com/Syncano/website.git ./repos/Syncano/website
git clone https://github.com/qbittorrent/qBittorrent-website.git ./repos/qbittorrent/qBittorrent-website
git clone https://github.com/typora/theme.typora.io.git ./repos/typora/theme.typora.io
git clone https://github.com/apple/swift-org-website.git ./repos/apple/swift-org-website
git clone https://github.com/freegate-release/website.git ./repos/freegate-release/website
git clone https://github.com/abetterinternet/website.git ./repos/abetterinternet/website
git clone https://github.com/midudev/miduconf-website.git ./repos/midudev/miduconf-website
git clone https://github.com/openebs/website.git ./repos/openebs/website
git clone https://github.com/apache/spark-website.git ./repos/apache/spark-website
git clone https://github.com/umutxyp/Personal-Website.git ./repos/umutxyp/Personal-Website
git clone https://github.com/ParryQiu/GuGuJianKong.git ./repos/ParryQiu/GuGuJianKong
git clone https://github.com/Bookshlf-in/Website.git ./repos/Bookshlf-in/Website
git clone https://github.com/Espresso-Aficionados/website.git ./repos/Espresso-Aficionados/website
git clone https://github.com/helfi92/studorlio.git ./repos/helfi92/studorlio
git clone https://github.com/department-of-veterans-affairs/vets-website.git ./repos/department-of-veterans-affairs/vets-website
git clone https://github.com/reactjs/zh-hans.react.dev.git ./repos/reactjs/zh-hans.react.dev
git clone https://github.com/open-telemetry/opentelemetry.io.git ./repos/open-telemetry/opentelemetry.io
git clone https://github.com/unhosted/website.git ./repos/unhosted/website
git clone https://github.com/apache/apisix-website.git ./repos/apache/apisix-website
git clone https://github.com/PHPGangsta/WebsiteToImage.git ./repos/PHPGangsta/WebsiteToImage
git clone https://github.com/akashyap2013/Books-bootstrap-website.git ./repos/akashyap2013/Books-bootstrap-website
git clone https://github.com/apache/servicecomb-website.git ./repos/apache/servicecomb-website
git clone https://github.com/coreui/coreui-website.git ./repos/coreui/coreui-website
git clone https://github.com/cplmakerlab/simple-website-template.git ./repos/cplmakerlab/simple-website-template
git clone https://github.com/bitcoin-core/bitcoincore.org.git ./repos/bitcoin-core/bitcoincore.org
git clone https://github.com/LubyRuffy/fofa.git ./repos/LubyRuffy/fofa
git clone https://github.com/RedHatGov/redhatgov.git ./repos/ub.io.git ./repos/RedHatGov/redhatgov.git ./repos/ub.io
git clone https://github.com/SauravMukherjee44/Aec-Library-Website.git ./repos/SauravMukherjee44/Aec-Library-Website
git clone https://github.com/carolineh101/Personal-Website.git ./repos/carolineh101/Personal-Website
git clone https://github.com/godotengine/godot-website.git ./repos/godotengine/godot-website
git clone https://github.com/inclusivenaming/website.git ./repos/inclusivenaming/website
git clone https://github.com/openhab/website.git ./repos/openhab/website
git clone https://github.com/dylanbai8/V2Ray_ws-tls_Website_onekey.git ./repos/dylanbai8/V2Ray_ws-tls_Website_onekey
git clone https://github.com/umutxyp/Discord-Bot-Website.git ./repos/umutxyp/Discord-Bot-Website
git clone https://github.com/volcano-sh/website.git ./repos/volcano-sh/website
git clone https://github.com/joshsoftware/website.git ./repos/joshsoftware/website
git clone https://github.com/daangn/websites.git ./repos/daangn/websites
git clone https://github.com/tech2etc/Build-and-Deploy-Ecommerce-Website.git ./repos/tech2etc/Build-and-Deploy-Ecommerce-Website
git clone https://github.com/TheAlgorithms/website-old.git ./repos/TheAlgorithms/website-old
git clone https://github.com/EuroPython/website.git ./repos/EuroPython/website
git clone https://github.com/CodeWithHarry/DanceWebsite.git ./repos/CodeWithHarry/DanceWebsite
git clone https://github.com/CodeWithHarry/DanceWebsite.git ./repos/CodeWithHarry/DanceWebsite
git clone https://github.com/regolith-linux/website.git ./repos/regolith-linux/website
git clone https://github.com/bevry/staticsitegenerators-website.git ./repos/bevry/staticsitegenerators-website
git clone https://github.com/winder/ugs_website.git ./repos/winder/ugs_website
git clone https://github.com/simple-login/website.git ./repos/simple-login/website
git clone https://github.com/IFmiss/vue-website.git ./repos/IFmiss/vue-website
git clone https://github.com/rajaprerak/rajaprerak.git ./repos/ub.io.git ./repos/rajaprerak/rajaprerak.git ./repos/ub.io
git clone https://github.com/XXIIVV/webring.git ./repos/XXIIVV/webring
git clone https://github.com/crosswalk-project/crosswalk-website.git ./repos/crosswalk-project/crosswalk-website
git clone https://github.com/bluesky-social/atproto-website.git ./repos/bluesky-social/atproto-website
git clone https://github.com/laravelnigeria/website.git ./repos/laravelnigeria/website
git clone https://github.com/dexidp/website.git ./repos/dexidp/website
git clone https://github.com/moja-global/community-website.git ./repos/moja-global/community-website
git clone https://github.com/briancodex/react-website-v2.git ./repos/briancodex/react-website-v2
git clone https://github.com/liorgrossman/darkness.git ./repos/liorgrossman/darkness
git clone https://github.com/protocol/nft-website.git ./repos/protocol/nft-website
git clone https://github.com/PFTL/website.git ./repos/PFTL/website
git clone https://github.com/sbryngelson/academic-website-template.git ./repos/sbryngelson/academic-website-template
git clone https://github.com/unjs/website.git ./repos/unjs/website
git clone https://github.com/dayjs/dayjs-website.git ./repos/dayjs/dayjs-website
git clone https://github.com/luisbraganca/fake-terminal-website.git ./repos/luisbraganca/fake-terminal-website
git clone https://github.com/codersgyan/Responsive-restaurant-website.git ./repos/codersgyan/Responsive-restaurant-website
git clone https://github.com/Vanilla-OS/website.git ./repos/Vanilla-OS/website
git clone https://github.com/microsoft/TypeScript-Handbook.git ./repos/microsoft/TypeScript-Handbook
git clone https://github.com/pnpm/pnpm.io.git ./repos/pnpm/pnpm.io
git clone https://github.com/m4tt72/terminal.git ./repos/m4tt72/terminal
git clone https://github.com/PaperMC/website.git ./repos/PaperMC/website
git clone https://github.com/robbin/robbin_site.git ./repos/robbin/robbin_site
git clone https://github.com/idangerous/website-templates.git ./repos/idangerous/website-templates
git clone https://github.com/choojs/website.git ./repos/choojs/website
git clone https://github.com/redox-os/website.git ./repos/redox-os/website
git clone https://github.com/BlackTimber-Labs/Portfolio-Website.git ./repos/BlackTimber-Labs/Portfolio-Website
git clone https://github.com/frida/frida-website.git ./repos/frida/frida-website
git clone https://github.com/ember-learn/ember-website.git ./repos/ember-learn/ember-website
git clone https://github.com/apache/guacamole-website.git ./repos/apache/guacamole-website
git clone https://github.com/SevenTV/Website.git ./repos/SevenTV/Website
git clone https://github.com/TeamWin/twrpme.git ./repos/TeamWin/twrpme
git clone https://github.com/pyistanbul/website.git ./repos/pyistanbul/website
git clone https://github.com/bedimcode/responsive-portfolio-website-Ansel.git ./repos/bedimcode/responsive-portfolio-website-Ansel
git clone https://github.com/lektor/lektor-website.git ./repos/lektor/lektor-website
